"""Default resume profile seed definitions."""

from __future__ import annotations

DEFAULT_LOCATIONS = ["Islamabad", "Rawalpindi", "Lahore", "Karachi", "Pakistan", "Remote"]

PROFILE_SEEDS: list[dict] = [
    {
        "name": "React Native Engineer",
        "slug": "react-native",
        "description": "Mobile / React Native / Expo focused roles",
        "resume_file": "react_native_resume",
        "title_keywords": [
            "React Native Engineer",
            "React Native Developer",
            "Mobile Developer",
            "React Native",
            "Mobile App Developer",
            "Cross Platform Developer",
            "Expo Developer",
        ],
        "min_experience_years": 1,
        "max_experience_years": 8,
        "education_keywords": ["Bachelor", "BS Computer Science", "BS IT"],
        "skills": [
            ("React Native", 10, True),
            ("React", 7, False),
            ("TypeScript", 7, False),
            ("JavaScript", 7, True),
            ("Expo", 8, False),
            ("Redux", 6, False),
            ("REST API", 6, False),
            ("Firebase", 6, False),
            ("Android", 5, False),
            ("iOS", 5, False),
        ],
    },
    {
        "name": "IT Support / Application Support",
        "slug": "it-support",
        "description": "IT Support, Help Desk, Application Support roles",
        "resume_file": "it_support_resume",
        "title_keywords": [
            "IT Support Engineer",
            "IT Support",
            "Application Support",
            "Application Support Engineer",
            "Technical Support",
            "IT Officer",
            "Help Desk",
            "Desktop Support",
            "System Support",
        ],
        "min_experience_years": 0,
        "max_experience_years": 10,
        "education_keywords": ["Bachelor", "BS IT", "Diploma"],
        "skills": [
            ("IT Support", 10, True),
            ("Windows", 8, True),
            ("Active Directory", 7, False),
            ("Networking", 7, False),
            ("TCP/IP", 6, False),
            ("DNS", 5, False),
            ("DHCP", 5, False),
            ("SQL", 5, False),
            ("macOS", 4, False),
        ],
    },
    {
        "name": "Teacher",
        "slug": "teacher",
        "description": "Computer / Mathematics teaching roles",
        "resume_file": "teacher_resume",
        "title_keywords": [
            "Computer Teacher",
            "Computer Science Teacher",
            "Mathematics Teacher",
            "Math Teacher",
            "Computer Instructor",
            "IT Teacher",
            "School Teacher",
            "Subject Teacher",
        ],
        "min_experience_years": 0,
        "max_experience_years": 15,
        "education_keywords": ["Bachelor", "Master", "B.Ed", "Computer Science", "Mathematics"],
        "remote_ok": False,
        "preferred_locations": ["Islamabad", "Rawalpindi", "Pakistan"],
        "skills": [
            ("Computer Science", 10, True),
            ("Mathematics", 9, False),
            ("Teaching", 10, True),
            ("Python", 4, False),
        ],
    },
    {
        "name": "Software / Full Stack Developer",
        "slug": "software-developer",
        "description": "Software, full stack, web development roles",
        "resume_file": "software_developer_resume",
        "title_keywords": [
            "Software Engineer",
            "Software Developer",
            "Full Stack Developer",
            "Backend Developer",
            "Frontend Developer",
            "Node.js Developer",
            "Python Developer",
            "Web Developer",
        ],
        "min_experience_years": 1,
        "max_experience_years": 10,
        "education_keywords": ["Bachelor", "BS Computer Science", "BS IT"],
        "skills": [
            ("JavaScript", 8, True),
            ("TypeScript", 7, False),
            ("Node.js", 8, False),
            ("React", 7, False),
            ("PostgreSQL", 6, False),
            ("MongoDB", 5, False),
            ("REST API", 7, False),
            ("Git", 6, False),
            ("Docker", 5, False),
            ("Next.js", 5, False),
        ],
    },
    {
        "name": "AI / Python",
        "slug": "ai-python",
        "description": "AI, Python, FastAPI, ML-related roles",
        "resume_file": "ai_resume",
        "title_keywords": [
            "AI Engineer",
            "Junior AI Engineer",
            "AI Developer",
            "Python Developer",
            "Python Engineer",
            "FastAPI Developer",
            "Machine Learning Engineer",
            "AI Application Engineer",
            "AI Business Intelligence",
            "LLM Engineer",
        ],
        "min_experience_years": 0,
        "max_experience_years": 8,
        "education_keywords": ["Bachelor", "BS Computer Science", "Master"],
        "skills": [
            ("Python", 10, True),
            ("FastAPI", 8, False),
            ("Machine Learning", 7, False),
            ("LLM", 7, False),
            ("PostgreSQL", 5, False),
            ("Docker", 5, False),
            ("REST API", 6, False),
            ("SQL", 5, False),
        ],
    },
    {
        "name": "Automation",
        "slug": "automation",
        "description": "n8n and workflow automation roles",
        "resume_file": "automation_resume",
        "title_keywords": [
            "n8n Developer",
            "Automation Engineer",
            "Workflow Automation",
            "AI Automation",
            "Automation Developer",
        ],
        "min_experience_years": 0,
        "max_experience_years": 8,
        "education_keywords": ["Bachelor", "BS IT"],
        "skills": [
            ("n8n", 10, True),
            ("Automation", 9, True),
            ("Zapier", 6, False),
            ("REST API", 6, False),
            ("JavaScript", 5, False),
            ("Python", 5, False),
            ("SQL", 4, False),
        ],
    },
]
