"""Default job search profile seed definitions (Phase 3 Step 2)."""

from __future__ import annotations

DEFAULT_LOCATIONS = ["Islamabad", "Rawalpindi", "Remote", "Pakistan"]
TEACHER_LOCATIONS = ["Islamabad", "Rawalpindi", "Pakistan"]
DEFAULT_REMOTE_TYPES = ["remote", "hybrid", "onsite", "unknown"]

# Maps search profile slug → resume profile slug for primary matching.
SEARCH_PROFILE_SEEDS: list[dict] = [
    {
        "name": "React Native Jobs",
        "slug": "react-native",
        "resume_profile_slug": "react-native",
        "keywords": [
            "React Native Engineer",
            "React Native Developer",
            "React Native",
            "Mobile Developer",
            "Mobile App Developer",
            "Expo Developer",
            "Cross Platform Developer",
        ],
        "locations": list(DEFAULT_LOCATIONS),
        "remote_types": list(DEFAULT_REMOTE_TYPES),
        "source": "mock",
        "enabled": True,
        "schedule_enabled": True,
        "schedule_interval_minutes": 60,
    },
    {
        "name": "IT Support Jobs",
        "slug": "it-support",
        "resume_profile_slug": "it-support",
        "keywords": [
            "IT Support",
            "IT Support Engineer",
            "Application Support",
            "Application Support Engineer",
            "Technical Support",
            "IT Officer",
            "Help Desk",
            "Desktop Support",
            "System Support",
        ],
        "locations": list(DEFAULT_LOCATIONS),
        "remote_types": list(DEFAULT_REMOTE_TYPES),
        "source": "mock",
        "enabled": True,
        "schedule_enabled": True,
        "schedule_interval_minutes": 120,
    },
    {
        "name": "Teaching Jobs",
        "slug": "teacher",
        "resume_profile_slug": "teacher",
        "keywords": [
            "Computer Teacher",
            "Computer Science Teacher",
            "Mathematics Teacher",
            "Math Teacher",
            "Computer Instructor",
            "IT Teacher",
        ],
        "locations": list(TEACHER_LOCATIONS),
        "remote_types": ["onsite", "hybrid", "unknown"],
        "source": "mock",
        "enabled": True,
        "schedule_enabled": True,
        "schedule_interval_minutes": 180,
    },
    {
        "name": "Software Developer Jobs",
        "slug": "software",
        "resume_profile_slug": "software-developer",
        "keywords": [
            "Software Engineer",
            "Software Developer",
            "Full Stack Developer",
            "Backend Developer",
            "Frontend Developer",
            "Node.js Developer",
            "Python Developer",
            "Web Developer",
        ],
        "locations": list(DEFAULT_LOCATIONS),
        "remote_types": list(DEFAULT_REMOTE_TYPES),
        "source": "mock",
        "enabled": True,
        "schedule_enabled": True,
        "schedule_interval_minutes": 60,
    },
    {
        "name": "AI Python Jobs",
        "slug": "ai-python",
        "resume_profile_slug": "ai-python",
        "keywords": [
            "AI Engineer",
            "Junior AI Engineer",
            "AI Developer",
            "AI Application Engineer",
            "Python Developer",
            "Python Engineer",
            "FastAPI Developer",
            "Machine Learning Engineer",
            "LLM Engineer",
        ],
        "locations": list(DEFAULT_LOCATIONS),
        "remote_types": list(DEFAULT_REMOTE_TYPES),
        "source": "mock",
        "enabled": True,
        "schedule_enabled": True,
        "schedule_interval_minutes": 60,
    },
    {
        "name": "Automation Jobs",
        "slug": "automation",
        "resume_profile_slug": "automation",
        "keywords": [
            "n8n Developer",
            "Automation Engineer",
            "AI Automation",
            "Workflow Automation",
            "Automation Developer",
        ],
        "locations": list(DEFAULT_LOCATIONS),
        "remote_types": list(DEFAULT_REMOTE_TYPES),
        "source": "mock",
        "enabled": True,
        "schedule_enabled": True,
        "schedule_interval_minutes": 120,
    },
]
